
const TrainingDataCore={
  VERSION:'4.4.3',
  _nutritionCache:Object.create(null),
  _cacheNutritionRow(r){if(!r)return;const date=String(r.summary_date||r.date||'').slice(0,10);if(!date)return;this._nutritionCache[date]={date,kcal:Number(r.calories_kcal??r.kcal??r.total_calories)||null,prot:Number(r.protein_g??r.protein)||null,carb:Number(r.carbohydrate_g??r.carbs_g??r.carb_g)||null,fat:Number(r.fat_g??r.fat)||null,fiber:Number(r.fiber_g??r.fiber)||null,source:'fatsecret'}},
  user:()=>window.TrainMeiState?.currentUser??window.__tp?.currentUser??null,
  training:(from,to)=>window.TrainMeiState?.getAnalyticsRows?.(from,to)??window.__tp?.getAnalyticsRows?.(from,to)??[],
  recovery:d=>window.tpRecoveryValues?window.tpRecoveryValues(d):null,
  recoveryScore:d=>window.tpRecoveryScore?window.tpRecoveryScore(d):null,
  trainingLoad:d=>window.tpWorkoutLoad?window.tpWorkoutLoad(d):0,
  totalTime:d=>d&&!d.restDay?Math.max(0,Number(d.metrics?.timeMin)||0):0,
  nutrition:()=>{const remote=window.TrainMeiNutritionData?.getSnapshot?.()||null,calc=window.TrainMeiNutri?.getSnapshot?.()||{};if(!remote)return{...calc,intake:{},source:'calculator'};return{...remote,targets:{...(calc.targets||{})},calculatorProfile:calc.profile||null};},
  body:()=>{const n=window.TrainMeiNutri?.getSnapshot?.();return n?{weight:n.weight||null}:null},
  cycle:()=>window.tpCycleSnapshot?window.tpCycleSnapshot():null,
  clamp(n,a=0,b=100){return Math.max(a,Math.min(b,Number(n)||0))},
  avg(a){return a.length?a.reduce((x,y)=>x+Number(y||0),0)/a.length:0},
  corr(a,b){if(a.length<5||b.length!==a.length)return 0;const ma=this.avg(a),mb=this.avg(b),sa=Math.sqrt(this.avg(a.map(x=>(x-ma)**2))),sb=Math.sqrt(this.avg(b.map(x=>(x-mb)**2)));return sa&&sb?this.avg(a.map((x,i)=>(x-ma)*(b[i]-mb)))/(sa*sb):0},
  dayKey(d=new Date()){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`},
  recoveryPercent(d){const rv=this.recovery(d);if(!rv||!rv.hasData)return null;const sub=[];if(Number(rv.sleep)>0)sub.push(Number(rv.sleep)/5*100);if(Number(rv.energy)>0)sub.push(Number(rv.energy)/5*100);if(Number(rv.soreness)>0)sub.push((6-Number(rv.soreness))/5*100);return sub.length?this.avg(sub):null},
  nutritionContext(date){const n=this.nutrition()||{},i=n.intake||{},t=n.targets||{},same=!date||!n.date||n.date===date;const cached=!same&&date?this._nutritionCache[String(date).slice(0,10)]:null;const intake={kcal:(same?i.kcal:cached?.kcal)!=null?Number(same?i.kcal:cached.kcal):null,carb:(same?i.carb:cached?.carb)!=null?Number(same?i.carb:cached.carb):null,prot:(same?i.prot:cached?.prot)!=null?Number(same?i.prot:cached.prot):null,fat:(same?i.fat:cached?.fat)!=null?Number(same?i.fat:cached.fat):null};const coverage={kcal:intake.kcal!=null&&Number(t.kcal)>0?Math.round(intake.kcal/Number(t.kcal)*100):null,carb:intake.carb!=null&&Number(t.carb)>0?Math.round(intake.carb/Number(t.carb)*100):null,prot:intake.prot!=null&&Number(t.prot)>0?Math.round(intake.prot/Number(t.prot)*100):null};return{date:date||n.date||null,source:same?(n.source||'fatsecret'):(cached?'fatsecret-history':'historical'),connected:same?!!n.connected:false,intake,targets:{kcal:Number(t.kcal)||null,carb:Number(t.carb)||null,prot:Number(t.prot)||null,fat:Number(t.fat)||null},coverage}},
  async nutritionHistory(from,to){const sb=window.supabaseClient;if(!sb)return[];try{if(window.TrainMeiNutritionData?.loadHistory){const h=await window.TrainMeiNutritionData.loadHistory(from,to);return(h?.summaries||[]).map(r=>({...r,date:String(r.summary_date||r.date||'').slice(0,10),kcal:Number(r.calories_kcal??r.kcal??r.total_calories)||null,prot:Number(r.protein_g??r.protein)||null,carb:Number(r.carbohydrate_g??r.carbs_g??r.carb_g)||null,fat:Number(r.fat_g??r.fat)||null,fiber:Number(r.fiber_g??r.fiber)||null,source:'fatsecret'}))}const {data,error}=await sb.from('nutrition_daily_summaries').select('*').gte('summary_date',from).lte('summary_date',to).order('summary_date',{ascending:true});if(error)return[];(data||[]).forEach(r=>this._cacheNutritionRow(r));return(data||[]).map(r=>({...r,date:String(r.summary_date||'').slice(0,10),kcal:Number(r.calories_kcal??r.kcal??r.total_calories)||null,prot:Number(r.protein_g??r.protein)||null,carb:Number(r.carbohydrate_g??r.carbs_g??r.carb_g)||null,fat:Number(r.fat_g??r.fat)||null,fiber:Number(r.fiber_g??r.fiber)||null,source:'fatsecret'}))}catch(e){return[]}},
  async nutritionEntriesHistory(from,to){const sb=window.supabaseClient;if(!sb)return[];try{const {data,error}=await sb.from('nutrition_entries').select('*').gte('entry_date',from).lte('entry_date',to).order('entry_date',{ascending:true});if(error)return[];const normalize=window.TrainMeiNutritionData?.normalizeNutritionEntry;return(data||[]).map(r=>normalize?normalize(r):({...r,consumptionTime:r.consumption_time??r.meal_time??r.entry_time??r.consumed_at??r.time??null}));}catch(e){return[]}},
  fuelRequirement(date,workout){
    const w=workout||null,d=this.trainingDemand(date,w);
    if(w?.restDay||d.restDay)return{date,restDay:true,carbs:0,preWorkoutCarbs:0,gramsPerKg:null,confidence:'High',basis:'rest-day'};
    const mins=Math.max(0,Number(d.duration)||0),distance=Math.max(0,Number(d.distance)||0),rpe=Math.max(0,Number(d.rpe)||0);
    let carbs=d.demand==='High'?45:d.demand==='Moderate'?30:20;
    if(mins>=90||distance>=12)carbs+=20;else if(mins>=60||distance>=7)carbs+=10;
    if(rpe>=8)carbs+=10;
    return{date,restDay:false,carbs,preWorkoutCarbs:Math.round(carbs*.45),gramsPerKg:null,confidence:(mins||distance||d.sets)?'Moderate':'Low',basis:'training-demand'};
  },
  nutritionBudget(date=null){
    const n=this.nutritionContext(date||this.dayKey()),t=n.targets||{},i=n.intake||{};
    const remaining=(target,used)=>target!=null&&used!=null?Math.max(0,Number(target)-Number(used)):null;
    return{date:date||this.dayKey(),source:n.source||'fatsecret',completeKcal:n.coverage?.kcal!=null,completeCarbs:n.coverage?.carb!=null,completeProtein:n.coverage?.prot!=null,targets:n.targets,intake:n.intake,remaining:{kcal:remaining(t.kcal,i.kcal),carb:remaining(t.carb,i.carb),prot:remaining(t.prot,i.prot),fat:remaining(t.fat,i.fat)}};
  },
  async nutritionTimingContext(date,workout=null){
    const key=date||this.dayKey(),entries=await this.nutritionEntriesHistory(key,key);
    const timed=entries.filter(e=>{const v=e?.consumptionTime??e?.consumption_time??e?.meal_time??null;return v!=null&&String(v).trim()});
    const sessionStart=workout?.metrics?.startTime||workout?.metrics?.sessionTime||workout?.startTime||workout?.sessionTime||null;
    const parseMinutes=v=>{const m=String(v??'').match(/(?:T|\s)?(\d{1,2}):(\d{2})/);return m?(Number(m[1])*60+Number(m[2])):null};
    const start=parseMinutes(sessionStart);
    const meals=timed.map(e=>{const time=e.consumptionTime??e.consumption_time??e.meal_time??null;const minutes=parseMinutes(time);return{time:String(time),minutes,meal:e.meal_name||e.meal||e.name||e.food_name||'Meal',kcal:Number(e.calories_kcal??e.kcal??e.calories)||null,carb:Number(e.carbohydrate_g??e.carbs_g??e.carb_g??e.carbs)||null,prot:Number(e.protein_g??e.protein)||null,preSession:start!=null&&minutes!=null?minutes<=start:null}});
    return{date:key,totalEntries:entries.length,timedEntries:meals.length,sessionStart:sessionStart||null,sessionStartKnown:start!=null,preSessionKnown:start!=null,preSessionMeals:meals.filter(x=>x.preSession===true),meals};
  },
  async optimizerContext(date,workout=null){
    const key=date||this.dayKey(),nutrition=this.nutritionContext(key),budget=this.nutritionBudget(key),demand=this.trainingDemand(key,workout),fuel=this.performanceFuel(key,workout),timing=await this.nutritionTimingContext(key,workout);
    return{date:key,nutrition,budget,demand,fuel,timing};
  },
  async sessionContext(date,workout=null){
    const key=date||this.dayKey(),ctx=await this.unifiedContext(key,workout);
    return{date:key,training:ctx.training,nutrition:ctx.nutrition,budget:ctx.budget,fuel:ctx.fuel,recovery:ctx.recovery,recoveryPercent:ctx.recoveryPercent,timing:ctx.timing,loadRatio:ctx.loadRatio,cycle:ctx.cycle};
  },
  async recordNutritionFeedback(feedback,workout=null){
    const f=feedback||{},date=f.date||this.dayKey(),ctx=await this.sessionContext(date,workout);
    return this.recordEvent({type:'nutrition_feedback',status:'Nutrition feedback linked to session context',date,payload:{...f,sessionContext:ctx,fuelScore:ctx.fuel?.score??null,fuelStatus:ctx.fuel?.status??null,preWorkoutCarbs:ctx.fuel?.preWorkoutCarbs??null,sessionDemand:ctx.training?.demand??null,sessionDuration:ctx.training?.duration??null,sessionDistance:ctx.training?.distance??null,sessionRpe:ctx.training?.rpe??null,remainingKcal:ctx.budget?.remaining?.kcal??null,remainingCarbs:ctx.budget?.remaining?.carb??null,remainingProtein:ctx.budget?.remaining?.prot??null,sessionStartKnown:!!ctx.timing?.sessionStartKnown,preSessionMeals:ctx.timing?.preSessionMeals?.length??0}});
  },
  plannedWorkout(date){try{return window.TrainMeiState?.planning?.getPlannedWorkout?.(date)||null;}catch(e){return null;}},
  trainingDemand(date,workout){let w=workout||null,planned=!w;if(!w){const _getRows=window.tpAllWorkoutRows||(window.TrainMeiState||window.__tp)?.allWorkoutRows;if(_getRows){try{w=(_getRows()||[]).find(r=>r.date===date)?.data||null}catch(e){}}}if(!w)w=this.plannedWorkout(date);if(!w)return{date,hasWorkout:false,planned:false,restDay:true,score:0,demand:'Rest day',type:'Rest day',load:0,volume:0,duration:0,distance:0,rpe:0,sets:0,conditioning:false,running:false,strength:false,timeSource:'none'};if(w.restDay)return{date,hasWorkout:false,planned,restDay:true,score:0,demand:'Rest day',type:'Rest day',load:0,volume:0,duration:0,distance:0,rpe:0,sets:0,conditioning:false,running:false,strength:false,timeSource:'explicit'};const blocks=Array.isArray(w.blocks)?w.blocks:[],ex=blocks.flatMap(b=>Array.isArray(b.exercises)?b.exercises:[]).filter(e=>String(e?.name||'').trim()),sets=ex.reduce((n,e)=>(e.setGroups||[e]).reduce((s,g)=>s+(Number(g?.sets)||0),n),0),volume=ex.reduce((n,e)=>(e.setGroups||[e]).reduce((s,g)=>s+(Number(g?.sets)||0)*(Number(String(g?.reps||'').match(/\d+(?:\.\d+)?/)?.[0])||0)*(Number(g?.weight)||0),n),0),metrics=w.metrics||{},text=JSON.stringify(w).toLowerCase(),distance=Number(metrics.distanceKm)||0,loggedDuration=Number(metrics.timeMin)||0,load=Number(metrics.load)||0,rpe=Number(metrics.rpe)||0,running=/run|running|row|cycling|bike/.test(text),strength=/strength|squat|deadlift|bench|press|pull|hypertrophy/.test(text),conditioning=/amrap|for time|emom|time cap|conditioning|hyrox/.test(text),estimatedDuration=loggedDuration||(running&&distance?Math.max(15,Math.round(distance*7.5)):(sets?Math.max(15,Math.round(sets*2.5)):conditioning?30:20)),timeSource=loggedDuration?'logged':'estimated',score=Math.min(100,Math.round((running?Math.min(35,distance*2.5):0)+(estimatedDuration?Math.min(30,estimatedDuration/3):0)+(volume?Math.min(20,volume/450):0)+(load?Math.min(15,load/5):0)+(rpe?Math.min(12,rpe*1.5):0)+(conditioning?10:0)));return{date,hasWorkout:true,planned,restDay:false,score,demand:score>=72?'High':score>=42?'Moderate':'Low',type:running?'Running / endurance':conditioning?'Conditioning':strength?'Strength':'Mixed training',sets,volume,distance,duration:estimatedDuration,loggedDuration,load,rpe,conditioning,running,strength,timeSource}},
  performanceFuel(date,workout,nutritionOverride=null){const base=this.nutrition(),n=nutritionOverride?{date,source:'fatsecret',connected:true,intake:{kcal:nutritionOverride.kcal??null,carb:nutritionOverride.carb??null,prot:nutritionOverride.prot??null,fat:nutritionOverride.fat??null},targets:{kcal:Number(base?.targets?.kcal)||null,carb:Number(base?.targets?.carb)||null,prot:Number(base?.targets?.prot)||null,fat:Number(base?.targets?.fat)||null},coverage:{kcal:nutritionOverride.kcal!=null&&base?.targets?.kcal?Math.round(nutritionOverride.kcal/base.targets.kcal*100):null,carb:nutritionOverride.carb!=null&&base?.targets?.carb?Math.round(nutritionOverride.carb/base.targets.carb*100):null,prot:nutritionOverride.prot!=null&&base?.targets?.prot?Math.round(nutritionOverride.prot/base.targets.prot*100):null}}:this.nutritionContext(date),d=this.trainingDemand(date,workout),c=n.coverage.carb,k=n.coverage.kcal,p=n.coverage.prot;if(c==null&&k==null&&p==null)return{date,score:null,status:'Insufficient data',demand:d,coverage:n.coverage,limitingFactor:null};const demandWeight=d.demand==='High'?1.15:d.demand==='Moderate'?1:.85,parts=[];if(c!=null)parts.push({v:this.clamp(c/demandWeight,0,120),w:.5,label:'Carbohydrate coverage'});if(k!=null)parts.push({v:this.clamp(k,0,120),w:.3,label:'Energy coverage'});if(p!=null)parts.push({v:this.clamp(p,0,120),w:.2,label:'Protein coverage'});const score=Math.round(parts.reduce((s,x)=>s+x.v*x.w,0)/parts.reduce((s,x)=>s+x.w,0)),status=score>=90?'Well fueled':score>=70?'Adequate':score>=50?'Needs attention':'Low fuel coverage',limiting=parts.reduce((a,b)=>b.v<a.v?b:a).label;const req=this.fuelRequirement(date,workout);return{date,score,status,demand:d,coverage:n.coverage,limitingFactor:limiting,fuelTarget:req,preWorkoutCarbs:req.preWorkoutCarbs}},
  async recentLoadRatio(refDateKey){const ref=new Date(refDateKey+'T12:00:00'),monday=new Date(ref);monday.setDate(ref.getDate()-((ref.getDay()+6)%7));const start=new Date(monday);start.setDate(monday.getDate()-21);const iso=d=>this.dayKey(d),rows=await this.training(iso(start),iso(new Date(monday.getFullYear(),monday.getMonth(),monday.getDate()+6))),by={};rows.forEach(r=>by[r.date]=this.trainingLoad(r.data));const week=w=>{const ss=new Date(monday);ss.setDate(monday.getDate()-w*7);let t=0;for(let i=0;i<7;i++){const d=new Date(ss);d.setDate(ss.getDate()+i);t+=by[iso(d)]||0}return t},total=week(0);let prev=0,n=0;for(let w=1;w<=3;w++){const x=week(w);if(x>0){prev+=x;n++}}const avgPrev=n?prev/n:total;return{ratio:avgPrev?total/avgPrev:1,hasData:total>0}},
  recoveryContext(date,dayData){const rv=this.recovery(dayData),rp=this.recoveryPercent(dayData),n=this.nutritionContext(date),fuel=this.performanceFuel(date,dayData);return{date,recovery:rv,recoveryPercent:rp,nutrition:n,fuel}},
  async unifiedContext(date,workout){const cycle=this.cycle()||{},demand=this.trainingDemand(date,workout),fuel=this.performanceFuel(date,workout),load=await this.recentLoadRatio(date),recovery=this.recovery(workout),recoveryPercent=this.recoveryPercent(workout),nutrition=this.nutritionContext(date),budget=this.nutritionBudget(date),timing=await this.nutritionTimingContext(date,workout);return{date,workout:workout||null,training:demand,nutrition,budget,recovery,recoveryPercent,fuel,timing,loadRatio:load.ratio,cycle,body:this.body()}},
  async learningEvents(){const local=[];try{const raw=JSON.parse(localStorage.getItem('training-planner:brain:v1')||'{}');if(Array.isArray(raw.events))local.push(...raw.events)}catch{};return local},
  foodTokens(items){const text=(Array.isArray(items)?items:[]).join(' ').toLowerCase();const known=['banana','apple','pear','blueberr','strawberr','raspberr','mango','kiwi','fruit','toast','bread','rice cake','rice cakes','oat','cereal','corn flakes','bagel','yogurt','skyr','cottage cheese','turkey','egg','chicken','rice','pasta','potato','pretzel','jam','honey','applesauce','cream of rice','peanut butter','milk'];return [...new Set(known.filter(k=>text.includes(k)))];},
  quickFoodPreferences(timing=null){const map={};try{const raw=JSON.parse(localStorage.getItem('training-planner:brain:v1')||'{}');for(const e of (raw.events||[])){if(e.type!=='nutrition_feedback')continue;const p=e.payload||e;if(timing!=null&&Number(p.timing)!==Number(timing))continue;const score=this.feedbackScore(p);if(score==null)continue;for(const food of this.foodTokens(p.mealItems||[])){map[food]??={n:0,sum:0};map[food].n++;map[food].sum+=score}}}catch{}return Object.entries(map).filter(([,v])=>v.n>=2).map(([food,v])=>({food,score:v.sum/v.n,n:v.n})).sort((a,b)=>b.score-a.score);},
  feedbackScore(e){const a=[Number(e?.tolerance),Number(e?.energy),Number(e?.performance)].filter(Number.isFinite).filter(v=>v>0);return a.length?this.avg(a):null},
  dataConfidence(profile){const p=profile||{},sample=Number(p.sample)||0,recent=Number(p.recentSample)||0,nut=Number(p.nutritionSample)||0,complete=Number(p.completeFeedbackSample)||0;const sampleScore=this.clamp(sample/12*40),recentScore=this.clamp(recent/6*20),nutritionScore=this.clamp(nut/14*15),feedbackScore=this.clamp(complete/6*15),consistency=Number(p.baseline?.consistency)||0,score=Math.round(this.clamp(sampleScore+recentScore+nutritionScore+feedbackScore+consistency*10));return{score,status:score>=80?'High':score>=55?'Moderate':score>=30?'Building':'Low',components:{sessions:sample,recentSessions:recent,nutritionDays:nut,feedbackSessions:complete}}},
  personalBaseline(sessions){const arr=(sessions||[]).filter(s=>s?.rpe>0);if(!arr.length)return{sample:0,rpe:null,duration:null,recovery:null,performance:null,consistency:0};const med=a=>{const x=a.filter(Number.isFinite).sort((m,n)=>m-n);return x.length?x[Math.floor(x.length/2)]:null},avg=a=>a.length?this.avg(a):null,rpes=arr.map(x=>Number(x.rpe)).filter(Number.isFinite),durations=arr.map(x=>Number(x.duration||x.data?.metrics?.timeMin)).filter(x=>x>0),recoveries=arr.map(x=>this.recoveryPercent(x.data)).filter(x=>x!=null),performances=arr.map(x=>Number(x.performance)).filter(x=>x>0),meanR=avg(rpes),sd=rpes.length>1?Math.sqrt(this.avg(rpes.map(x=>(x-meanR)**2))):0,consistency=rpes.length?this.clamp(1-sd/3,0,1):0;return{sample:arr.length,rpe:med(rpes),duration:med(durations),recovery:med(recoveries),performance:med(performances),consistency}},
  recoveryLagProfile(sessions,rows){const by=new Map((rows||[]).map(r=>[r.date,r.data||{}]));const lags={24:[],48:[],72:[]};for(const s of sessions||[]){const base=new Date(s.date+'T12:00:00');[24,48,72].forEach(h=>{const d=new Date(base);d.setHours(d.getHours()+h);const key=this.dayKey(d),v=this.recoveryPercent(by.get(key));if(v!=null)lags[h].push(v)});}return Object.fromEntries(Object.entries(lags).map(([h,a])=>[h,{sample:a.length,average:a.length?Math.round(this.avg(a)):null}]));},
  async learningProfile(from,to){
    const [rows,nutrition,entries,events]=await Promise.all([this.training(from,to),this.nutritionHistory(from,to),this.nutritionEntriesHistory(from,to),this.learningEvents()]);
    const nm=new Map(nutrition.map(x=>[x.date,x]));
    const sessions=rows.filter(r=>r.data?.completed).map(r=>{const d=r.data||{},rv=this.recovery(d)||{},n=nm.get(r.date)||null,f=this.performanceFuel(r.date,d,n),sf=d.sessionFeedback||{};return{date:r.date,data:d,rpe:Number(d.metrics?.rpe)||0,load:this.trainingLoad(d),volume:Number(d.metrics?.volume)||0,sets:this.trainingDemand(r.date,d).sets,duration:Number(d.metrics?.timeMin)||0,sleep:Number(rv.sleep)||0,energy:Number(rv.energy)||0,soreness:Number(rv.soreness)||0,carb:n?.carb??null,kcal:n?.kcal??null,prot:n?.prot??null,fuel:f.score,performance:Number(sf.performance)||null,technique:Number(sf.technique)||null,feelings:sf.feelings||'',adjustNextTime:sf.adjustNextTime||'',adjustmentOutcome:sf.adjustmentOutcome||'',cyclePhase:sf.cyclePhase||null,feedback:sf}});
    const patterns=[];const add=(kind,text,n,confidence)=>patterns.push({kind,text,n,confidence});
    const comparable=(field,min=6)=>sessions.filter(s=>Number.isFinite(Number(s.rpe))&&s.rpe>0&&s[field]!=null&&Number.isFinite(Number(s[field])));
    const addCorr=(field,label,direction='RPE',min=6)=>{const arr=comparable(field);if(arr.length<min)return;const c=this.corr(arr.map(x=>Number(x[field])),arr.map(x=>Number(x[direction==='RPE'?'rpe':'performance'])));if(Math.abs(c)>=.25)add(`${label} ↔ ${direction}`,`Your logged ${label.toLowerCase()} and ${direction.toLowerCase()} show a correlation of ${c.toFixed(2)} across ${arr.length} comparable sessions.`,arr.length,this.clamp(50+Math.abs(c)*45,50,94))};
    const usable=sessions.filter(s=>s.rpe>0&&s.fuel!=null);if(usable.length>=6){const hi=usable.filter(s=>s.fuel>=85),lo=usable.filter(s=>s.fuel<65);if(hi.length>=3&&lo.length>=3){const a=this.avg(hi.map(x=>x.rpe)),b=this.avg(lo.map(x=>x.rpe));if(Math.abs(a-b)>=.4)add('Fuel ↔ RPE',`Higher-fuel sessions averaged RPE ${a.toFixed(1)} vs ${b.toFixed(1)} on lower-fuel sessions.`,usable.length,this.clamp(55+Math.abs(a-b)*18,55,92));const hp=hi.filter(x=>x.performance!=null),lp=lo.filter(x=>x.performance!=null);if(hp.length>=3&&lp.length>=3){const ap=this.avg(hp.map(x=>x.performance)),bp=this.avg(lp.map(x=>x.performance));if(Math.abs(ap-bp)>=.4)add('Fuel ↔ Performance',`Higher-fuel sessions averaged performance ${ap.toFixed(1)}/10 vs ${bp.toFixed(1)}/10 on lower-fuel sessions.`,hp.length+lp.length,this.clamp(55+Math.abs(ap-bp)*18,55,92));}}}
    addCorr('sleep','Sleep');addCorr('energy','Energy');addCorr('soreness','Soreness','performance');addCorr('load','Load','performance');addCorr('load','Load','RPE');addCorr('volume','Volume','performance');
    const carbRpe=sessions.filter(s=>s.carb!=null&&s.rpe>0);if(carbRpe.length>=6){const c=this.corr(carbRpe.map(x=>Number(x.carb)),carbRpe.map(x=>Number(x.rpe)));if(Math.abs(c)>=.25)add('Carbohydrate ↔ RPE',`Logged carbohydrate intake and RPE show a correlation of ${c.toFixed(2)} across ${carbRpe.length} comparable sessions. This is an association in your logged data, not proof that carbohydrate intake caused the RPE change.`,carbRpe.length,this.clamp(50+Math.abs(c)*45,50,94))}
    const carbPerf=sessions.filter(s=>s.carb!=null&&s.performance!=null);if(carbPerf.length>=6){const c=this.corr(carbPerf.map(x=>Number(x.carb)),carbPerf.map(x=>Number(x.performance)));if(Math.abs(c)>=.25)add('Carbohydrate ↔ Performance',`Logged carbohydrate intake and session performance show a correlation of ${c.toFixed(2)} across ${carbPerf.length} comparable sessions. Treat this as a personal signal to monitor, not a causal conclusion.`,carbPerf.length,this.clamp(50+Math.abs(c)*45,50,94))}
    const loadRecovery=sessions.filter(s=>s.load>0&&this.recoveryPercent(s.data)!=null);if(loadRecovery.length>=6){const c=this.corr(loadRecovery.map(x=>x.load),loadRecovery.map(x=>this.recoveryPercent(x.data)));if(Math.abs(c)>=.25)add('Load ↔ Recovery',`Recent session load and recovery show a correlation of ${c.toFixed(2)} across ${loadRecovery.length} sessions.`,loadRecovery.length,this.clamp(50+Math.abs(c)*45,50,94))}
    const nutritionRecovery=sessions.filter(s=>s.fuel!=null&&this.recoveryPercent(s.data)!=null);if(nutritionRecovery.length>=6){const c=this.corr(nutritionRecovery.map(x=>x.fuel),nutritionRecovery.map(x=>this.recoveryPercent(x.data)));if(Math.abs(c)>=.25)add('Nutrition ↔ Recovery',`Fuel coverage and recovery show a correlation of ${c.toFixed(2)} across ${nutritionRecovery.length} sessions.`,nutritionRecovery.length,this.clamp(50+Math.abs(c)*45,50,94))}
    const foodFeedback=events.filter(e=>e.type==='nutrition_feedback'&&Array.isArray(e.payload?.mealItems));const foodMap={};foodFeedback.forEach(e=>{const score=this.feedbackScore(e.payload);if(score==null)return;for(const food of this.foodTokens(e.payload.mealItems)){foodMap[food]??={n:0,sum:0,byTiming:{}};foodMap[food].n++;foodMap[food].sum+=score;const t=Number(e.payload.timing)||0;foodMap[food].byTiming[t]??={n:0,sum:0};foodMap[food].byTiming[t].n++;foodMap[food].byTiming[t].sum+=score;}});
    const foodPreferences=Object.entries(foodMap).map(([food,v])=>{const best=Object.entries(v.byTiming).sort((a,b)=>b[1].sum/b[1].n-a[1].sum/a[1].n)[0];return{food,n:v.n,score:v.sum/v.n,bestTiming:best?Number(best[0]):null}}).filter(x=>x.n>=1).sort((a,b)=>b.score-a.score);if(foodPreferences.length){const strong=foodPreferences.filter(x=>x.n>=2).slice(0,5);if(strong.length)add('Food response',strong.map(x=>`${x.food}: ${x.score.toFixed(1)}/5${x.bestTiming?` around ${x.bestTiming} min`:''}`).join(' · '),foodFeedback.length,this.clamp(50+strong.length*8,50,90));}
    const phaseEvents=events.filter(e=>e.type==='session_feedback'&&e.payload?.cyclePhase);for(const phase of [...new Set(phaseEvents.map(e=>e.payload.cyclePhase))]){const pe=phaseEvents.filter(e=>e.payload.cyclePhase===phase&&Number(e.payload.rpe)>0);if(pe.length>=3){const a=this.avg(pe.map(e=>Number(e.payload.rpe)));add(`Cycle phase ↔ RPE (${phase})`,`Logged sessions in ${phase} averaged RPE ${a.toFixed(1)} across ${pe.length} sessions.`,pe.length,this.clamp(55+pe.length*5,55,88));}}
    const adjustmentEvents=events.filter(e=>e.type==='session_adjustment'&&e.payload);const outcomes=adjustmentEvents.filter(e=>e.payload.outcome);if(outcomes.length>=3){const worked=outcomes.filter(e=>['worked','better','yes','improved'].includes(String(e.payload.outcome).toLowerCase())).length;add('Adjustment ↔ Outcome',`${worked} of ${outcomes.length} logged adjustments were marked as working or improving the next session.`,outcomes.length,this.clamp(50+outcomes.length*7,50,90));}
    const baseline=this.personalBaseline(sessions),recentSample=sessions.filter(s=>s.date>=this.dayKey(Date.now()-42*86400000)).length,recoveryLag=this.recoveryLagProfile(sessions,rows),completeFeedbackSample=sessions.filter(s=>{const f=s.feedback||{};return Number(f.performance)>0||Number(f.energyRating)>0||Number(f.technique)>0||String(f.feelings||'').trim()||String(f.adjustNextTime||'').trim()}).length;const rpePerformance=sessions.filter(s=>s.rpe>0&&s.performance!=null);if(rpePerformance.length>=4){const high=rpePerformance.filter(s=>s.rpe>=8),low=rpePerformance.filter(s=>s.rpe<=5);if(high.length>=2&&low.length>=2){const hp=this.avg(high.map(s=>s.performance)),lp=this.avg(low.map(s=>s.performance));if(hp<lp-.5)patterns.push({kind:'RPE ↔ Performance calibration',text:`Higher-RPE sessions averaged ${hp.toFixed(1)}/10 performance vs ${lp.toFixed(1)}/10 at RPE ≤5. Use RPE as a progression gate, not only a target.`,n:rpePerformance.length,confidence:this.clamp(55+Math.abs(hp-lp)*12,55,92)});else if(hp>lp+.5)patterns.push({kind:'RPE ↔ Performance calibration',text:`Higher-RPE sessions averaged ${hp.toFixed(1)}/10 performance vs ${lp.toFixed(1)}/10 at RPE ≤5. Your higher effort has sometimes been productive; keep monitoring recovery.`,n:rpePerformance.length,confidence:this.clamp(55+Math.abs(hp-lp)*12,55,92)});}}const mealTimes=entries.map(e=>e.consumptionTime).filter(Boolean);if(mealTimes.length){const hourOf=v=>{const m=String(v).match(/(?:T|\s)(\d{1,2}):/);return m?Number(m[1]):null};const hours=mealTimes.map(hourOf).filter(h=>h!=null&&h>=0&&h<24);if(hours.length>=3)patterns.push({kind:'FatSecret meal timing',text:`${hours.length} imported meals include a consumption time; Nutrition Optimizer can use the timing alongside training demand when available.`,n:hours.length,confidence:this.clamp(50+hours.length*4,50,90)})}for(const [h,v] of Object.entries(recoveryLag)){if(v.sample>=3)patterns.push({kind:`Recovery +${h}h`,text:`Average logged recovery ${h}h after sessions: ${v.average}%.`,n:v.sample,confidence:this.clamp(55+v.sample*5,55,90)})}return{generatedAt:new Date().toISOString(),sample:sessions.length,recentSample,nutritionSample:nutrition.length,nutritionEntrySample:entries.length,completeFeedbackSample,baseline,recoveryLag,patterns,events:events.filter(e=>/feedback|adjustment|cycle|session|nutrition/i.test(e.type||'')),sessions,nutrition,foodPreferences,dataConfidence:this.dataConfidence({sample:sessions.length,recentSample,nutritionSample:nutrition.length,completeFeedbackSample,baseline})};
  },
  adaptation(context,profile){const c=context||{},p=profile||{},actions=[],signals=[];const fuel=c.fuel?.score,recovery=c.recoveryPercent,load=c.loadRatio,cycle=c.cycle||{},training=c.training||{},baseline=p.baseline||{};if(training.restDay){actions.push('Rest day detected: no training demand. Use the day for recovery, nutrition and optional light mobility only.');signals.push('Explicit or empty training day')}else if(recovery!=null&&recovery<55){actions.push('Reduce intensity or accessory volume today; keep the main movement technically controlled.');signals.push('Recovery below your observed range')}else if(recovery!=null&&recovery<70){actions.push('Keep planned load stable and use RPE/technique as the progression gate.');signals.push('Recovery moderate')}if(baseline.rpe!=null&&training.rpe>=baseline.rpe+1){actions.push(`Today’s RPE is about ${Math.round(training.rpe-baseline.rpe)} point above your personal baseline; avoid automatic progression unless performance and recovery support it.`);signals.push('RPE above personal baseline')}if(fuel!=null&&fuel<60)actions.push('Prioritize fueling around the session; avoid treating low fuel as a reason to force higher intensity.');if(load!=null&&load>1.18)actions.push('Recent load is elevated versus your prior weeks; avoid adding volume unless execution is clearly strong.');if(cycle.phase==='menstrual')actions.push('Period logged: use your own observed response as the primary guide; if symptoms or recovery are worse than usual, reduce intensity, impact or volume and extend recovery.');const phasePattern=(p.patterns||[]).find(x=>String(x.kind).includes('Cycle phase ↔')&&String(x.kind).includes(cycle.phase||'___'));if(phasePattern)actions.push(`Your history shows a phase-specific response (${phasePattern.text}). Use it as context, not as a fixed rule.`);const food=p.foodPreferences?.filter(x=>x.n>=2)?.[0];if(food&&food.score>=4)actions.push(`A repeatedly well-tolerated option is ${food.food}; Nutrition Optimizer can prioritize it when timing and training demand match.`);if(!actions.length)actions.push('No strong limiter detected. Follow the planned session and let execution feedback determine progression.');return{actions,signals,cycleImpact:cycle.phase?`Cycle context: ${cycle.phase}.`:'No cycle phase logged.',confidence:p.sample>=12?'High':p.sample>=6?'Moderate':'Low'}},
  readiness(dayData,context={}){if(dayData?.restDay||context.training?.restDay)return{score:null,status:'Rest day',confidence:context.training?.timeSource==='none'?'Detected':'Explicit',factors:[{label:'Training demand',value:0}],mainLimitingFactor:null};const parts=[],factors=[],rp=this.recoveryPercent(dayData);if(rp!=null){parts.push({value:rp,weight:.4});factors.push({label:'Recovery',value:rp})}if(context.loadRatio!=null){const v=this.clamp(100-Math.abs(context.loadRatio-1)*60,15,100);parts.push({value:v,weight:.25});factors.push({label:'Recent training load',value:v})}if(context.fuelScore!=null){parts.push({value:this.clamp(context.fuelScore),weight:.2});factors.push({label:'Performance fuel',value:context.fuelScore})}if(context.cyclePhase){const v={menstrual:60,follicular:70,ovulatory:72,luteal:64}[context.cyclePhase]??65;parts.push({value:v,weight:.15});factors.push({label:'Cycle context',value:v})}if(!parts.length)return{score:null,status:'No data yet',confidence:'insufficient data',factors:[],mainLimitingFactor:null};const score=Math.round(parts.reduce((s,p)=>s+p.value*p.weight,0)/parts.reduce((s,p)=>s+p.weight,0)),status=score>=75?'Training normally':score>=55?'Adjust intensity':'Recovery-focused session';return{score,status,confidence:factors.length>=3?'Good confidence':factors.length===2?'Moderate confidence':'Low confidence',factors,mainLimitingFactor:factors.reduce((a,b)=>b.value<a.value?b:a).label}},
  async getUnifiedProfile(days=365){const to=this.dayKey(),from=this.dayKey(Date.now()-days*86400000);return this.learningProfile(from,to)},
  async getUnifiedContext(date,workout){const c=await this.unifiedContext(date,workout),p=await this.getUnifiedProfile(365);return{...c,profile:p,adaptation:this.adaptation(c,p)}},
  recordEvent(event){const e={...event,id:`${Date.now()}_${Math.random().toString(36).slice(2,8)}`,createdAt:new Date().toISOString()};try{const raw=JSON.parse(localStorage.getItem('training-planner:brain:v1')||'{}');raw.events=[...(raw.events||[]),e].slice(-500);localStorage.setItem('training-planner:brain:v1',JSON.stringify(raw))}catch{};document.dispatchEvent(new CustomEvent('trainmei:core-learning',{detail:e}));return e},
  async personalInsights(from,to){const p=await this.learningProfile(from,to);return{sample:p.sample,insights:p.patterns,sessions:p.sessions,nutritionSample:p.nutritionSample,nutritionEntrySample:p.nutritionEntrySample,foodPreferences:p.foodPreferences}},
};
window.TrainingDataCore=TrainingDataCore;

(()=>{const _warm=async()=>{try{const user=TrainingDataCore.user();if(!user)return;const to=TrainingDataCore.dayKey();const from=TrainingDataCore.dayKey(Date.now()-180*86400000);await TrainingDataCore.nutritionHistory(from,to);}catch{}};document.addEventListener('trainmei:user-ready',_warm,{once:true});setTimeout(_warm,3000);})();