/* ===== SMART INTEGRATIONS OCR ===== */
(function(){
  const OCRKEY='training-planner:smart-imports';
  let reviewWorkout=null, reviewSourceText='', reviewConfidence=[];
  const $i=s=>document.querySelector(s);
  const escI=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cleanI=s=>String(s||'').replace(/\s+/g,' ').trim();
  const readImports=()=>{try{return JSON.parse(localStorage.getItem(OCRKEY)||'[]')}catch{return[]}};
  const saveImports=a=>localStorage.setItem(OCRKEY,JSON.stringify(a.slice(0,12)));
  const canonicalOCR=name=>{const n=cleanI(name), c=n.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();const map={'rdl':'RDL','romanian deadlift':'RDL','romanian dl':'RDL','peso muerto rumano':'RDL','back squat':'Back Squat','squat':'Back Squat','sentadilla':'Back Squat','bench press':'Bench Press','press banca':'Bench Press','wall ball':'Wall Balls','wall balls':'Wall Balls','kb swing':'KB Swings','kb swings':'KB Swings','kettlebell swing':'KB Swings','devil press':'Devil Press','burpee':'Burpee','row':'Row','rowing':'Row','overhead lunge':'Overhead Lunges','walking lunge':'Walking Lunges','plank pull through':'Plank Pull Through','weighted sit up':'Weighted Sit Up','weighted sit up s':'Weighted Sit Up','around the world lunge':'Around the World Lunge','plate thruster':'Plate Thruster','run':'Run','running':'Run'};if(map[c])return map[c];return n};
  function normalizeOCRSet(g){return {sets:String(g?.sets??''),reps:String(g?.reps??''),weight:String(g?.weight??''),type:g?.type||'Aprox'}}
  function makeExercise(name,groups){const gs=(groups&&groups.length?groups:[{}]).map(normalizeOCRSet);return {name:canonicalOCR(name),originalName:cleanI(name),setGroups:gs,sets:gs[0].sets,reps:gs[0].reps,weight:gs[0].weight}}
  function blankWorkout(){return {focus:'Imported workout',trainingCategory:'Garmin Import',blocks:[],isRunDay:false,runningRowing:{type:'Run',warmUp:{duration:'',details:''},mainSet:'',coolDown:{duration:'',details:''},blocks:[]},metrics:{distanceKm:'',timeMin:''},caffeine:{taken:false,mg:''},recovery:{sleep:0,energy:0,soreness:0},completed:false,notes:'',noteTags:[],importMeta:{source:'Garmin OCR'}}}
  function parseType(s){const c=cleanI(s).toLowerCase();if(/\bds\b|drop/.test(c))return'DS';if(/\bts\b|top set/.test(c))return'TS';if(/\bapprox?\b|\baprox\b|\baprx\b/.test(c))return'Aprox';return''}
  function parseOCRText(text){
    const lines=String(text||'').split(/\n+/).map(cleanI).filter(Boolean);const w=blankWorkout();let block={name:'Block 1',category:'Strength',exercises:[]};let runBlock=null;const warnings=[];
    const addBlock=()=>{if(block.exercises.length){w.blocks.push(block)};block={name:`Block ${w.blocks.length+1}`,category:'Strength',exercises:[]}};
    const exerciseLine=/^(?:\d+[.)]\s*)?([A-Za-z][A-Za-z0-9 &'’\-\/]+?)(?:\s+)(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)\s*(?:@|at|x|×)?\s*(\d+(?:\.\d+)?)?\s*(kg|lb|lbs)?\s*(.*)$/i;
    const compactSet=/^(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)\s+(\d+(?:\.\d+)?)?(?:\s*(Aprox|Approx|TS|DS))?$/i;
    let lastEx=null;
    for(const line of lines){
      const low=line.toLowerCase();
      if(/^(block|bloc)\s*\d*/i.test(line)){if(block.exercises.length)addBlock();block.name=line.replace(/^(block|bloc)\s*/i,'Block ');lastEx=null;continue}
      const run=low.match(/(\d+(?:\.\d+)?)\s*km\s*(?:run)?\s*(?:@|at|pace)?\s*(\d{1,2}[:.]\d{2})\s*(?:min\/km|\/km|km)?/i);
      if(run){runBlock={name:'Run',category:'Running',exercises:[makeExercise('Run',[{sets:1,reps:run[1]+' km',weight:run[2],type:'Aprox'}])]};w.blocks.push(runBlock);w.isRunDay=true;w.metrics.distanceKm=run[1];lastEx=runBlock.exercises[0];continue}
      const ex=line.match(exerciseLine);
      if(ex){const name=cleanI(ex[1]).replace(/[:\-]+$/,'');const g={sets:ex[2],reps:ex[3],weight:ex[4]||'',type:parseType(ex[6])||'Aprox'};lastEx=makeExercise(name,[g]);block.exercises.push(lastEx);continue}
      const cs=line.match(compactSet);
      if(cs&&lastEx){lastEx.setGroups.push(normalizeOCRSet({sets:cs[1],reps:cs[2],weight:cs[3]||'',type:parseType(cs[4])||'Aprox'}));continue}
      const dist=low.match(/(?:distance|dist)\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*km/);if(dist){w.metrics.distanceKm=dist[1];continue}
      if(/pace|ritmo/.test(low)){const pace=line.match(/(\d{1,2}[:.]\d{2})/);if(pace&&runBlock?.exercises[0])runBlock.exercises[0].setGroups[0].weight=pace[1];continue}
      if(/^(strength|conditioning|hyrox|running|run|lower body|upper body)/i.test(line)&&!block.exercises.length){block.category=line;continue}
    }
    if(block.exercises.length)addBlock();
    if(!w.blocks.length){warnings.push('No structured exercise rows were confidently detected.');w.blocks=[{name:'Block 1',category:'Imported',exercises:[makeExercise('Check exercise',[{sets:'',reps:'',weight:'',type:'Aprox'}])]}]}
    w.focus=w.blocks.length===1&&w.blocks[0].category==='Running'?'Run':'Imported Garmin workout';
    reviewConfidence=lines.map(x=>({line:x,ok:/\d/.test(x)&&(/[x×]/.test(x)||/km/.test(x))}));
    return {workout:w,warnings};
  }
  async function loadTesseract(){
    if(window.Tesseract)return window.Tesseract;
    return new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';sc.onload=()=>window.Tesseract?resolve(window.Tesseract):reject(new Error('OCR engine unavailable'));sc.onerror=()=>reject(new Error('Could not load the OCR engine. Check your connection and try again.'));document.head.appendChild(sc)});
  }
  async function preprocess(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);x.filter='grayscale(1) contrast(1.15)';x.drawImage(c,0,0);resolve(c.toDataURL('image/png'))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
  async function analyzeSmartScreenshot(){const f=$i('#smart-screenshot-file')?.files?.[0];if(!f)return;smartFileName=f.name;const status=$i('#smart-status');status.textContent='Preparing screenshot…';$i('#smart-preview-wrap').hidden=false;const reader=new FileReader();reader.onload=()=>{$i('#smart-preview').src=reader.result};reader.readAsDataURL(f);try{const image=await preprocess(f);status.textContent='Loading OCR engine…';const T=await loadTesseract();status.textContent='Reading screenshot…';const worker=await T.createWorker('eng');const res=await worker.recognize(image);const text=res.data?.text||'';const parsed=parseOCRText(text);reviewSourceText=text;reviewWorkout=parsed.workout;reviewWorkout.importMeta={source:'Garmin OCR',fileName:f.name,importedAt:new Date().toISOString()};reviewWorkout._ocrWarnings=parsed.warnings;reviewWorkout._ocrConfidence=res.data?.confidence||0;renderSmartReview();saveRecentImport(reviewWorkout,f.name);await worker.terminate();status.textContent=`Detected ${countExercises(reviewWorkout)} exercises · ${countSets(reviewWorkout)} sets · review before import`;}catch(err){console.error(err);status.textContent=err.message||'OCR failed';}}
  function countExercises(w){return (w.blocks||[]).reduce((n,b)=>n+(b.exercises||[]).filter(e=>e.name).length,0)}
  function countSets(w){return (w.blocks||[]).reduce((n,b)=>n+(b.exercises||[]).reduce((s,e)=>s+(e.setGroups||[]).length,0),0)}
  function renderSmartReview(){const w=reviewWorkout;if(!w)return;const ex=countExercises(w),sets=countSets(w),conf=Math.round(w._ocrConfidence||0);$i('#smart-review-summary').innerHTML=`<span>${w.blocks.length} blocks</span><span>${ex} exercises</span><span>${sets} set rows</span><span>${conf>=80?'High confidence':'Check values'}</span>`;const warn=w._ocrWarnings||[];const box=$i('#smart-review-warning');box.hidden=!warn.length;box.textContent=warn.length?`Review: ${warn.join(' ')}`:'';$i('#smart-review-content').innerHTML=(w.blocks||[]).map((b,bi)=>`<section class="smart-review-block" data-rblock="${bi}"><div class="smart-review-block-head"><input data-rblock-name value="${escI(b.name||`Block ${bi+1}`)}"><button type="button" class="btn" data-rblock-remove>Remove block</button></div><div class="smart-review-labels"><span>Exercise</span><span>Sets</span><span>Reps</span><span>Weight</span><span>Type</span><span></span></div>${(b.exercises||[]).map((e,ei)=>(e.setGroups||[]).map((g,gi)=>`<div class="smart-review-ex" data-rex="${bi}:${ei}:${gi}"><input class="ex-name" data-rex-name value="${escI(e.name)}" title="Original OCR: ${escI(e.originalName||e.name)}"><input data-rex-sets value="${escI(g.sets)}"><input data-rex-reps value="${escI(g.reps)}"><input data-rex-weight value="${escI(g.weight)}"><select data-rex-type><option ${g.type==='Aprox'?'selected':''}>Aprox</option><option ${g.type==='TS'?'selected':''}>TS</option><option ${g.type==='DS'?'selected':''}>DS</option></select><button type="button" class="btn" data-rex-remove aria-label="Remove set">×</button></div>`).join('')).join('')}<div class="smart-review-add"><button type="button" class="btn" data-rex-add>Add set</button><button type="button" class="btn" data-ex-add>Add exercise</button></div></section>`).join('')+`<div class="smart-review-add"><button type="button" class="btn" data-block-add>+ Add block</button></div>`;$i('#smart-review-modal').classList.add('show')}
  function syncReview(){if(!reviewWorkout)return;document.querySelectorAll('[data-rblock]').forEach((el,bi)=>{const b=reviewWorkout.blocks[bi];if(!b)return;b.name=el.querySelector('[data-rblock-name]')?.value||b.name;el.querySelectorAll('[data-rex]').forEach((row)=>{const [ei,gi]=row.dataset.rex.split(':').slice(1).map(Number);const e=b.exercises[ei];const g=e?.setGroups?.[gi];if(!e||!g)return;e.name=row.querySelector('[data-rex-name]')?.value||e.name;g.sets=row.querySelector('[data-rex-sets]')?.value||'';g.reps=row.querySelector('[data-rex-reps]')?.value||'';g.weight=row.querySelector('[data-rex-weight]')?.value||'';g.type=row.querySelector('[data-rex-type]')?.value||'Aprox';e.sets=e.setGroups[0]?.sets||'';e.reps=e.setGroups[0]?.reps||'';e.weight=e.setGroups[0]?.weight||''})})}
  function smartDayData(){const w=clone(reviewWorkout||{});delete w._ocrWarnings;delete w._ocrConfidence;delete w._ocrSourceText;w.blocks=(w.blocks||[]).map(b=>({...b,exercises:(b.exercises||[]).map(e=>({...e,originalName:undefined}))}));return typeof normalizeDay==='function'?normalizeDay(w):w}
  function clone(x){return JSON.parse(JSON.stringify(x))}
  function saveRecentImport(w,name){const a=readImports().filter(x=>x.id!==w.importMeta?.id);a.unshift({id:'ocr_'+Date.now(),name:name||w.importMeta?.fileName||'Garmin import',date:new Date().toISOString(),workout:clone(w),confidence:w._ocrConfidence||0});w.importMeta.id=a[0].id;saveImports(a);renderRecentImports()}
  function renderRecentImports(){const el=$i('#smart-recent-imports');if(!el)return;const a=readImports();el.innerHTML=a.length?a.map(x=>`<div class="smart-int-import"><div><strong>${escI(x.name)}</strong><small>${new Date(x.date).toLocaleDateString()} · ${Math.round(x.confidence||0)}% OCR confidence · ${countExercises(x.workout)} exercises</small></div><button type="button" class="btn" data-recent-id="${escI(x.id)}">Review</button></div>`).join(''):'<div class="smart-int-note">No imports yet. Your reviewed Garmin screenshots will appear here.</div>'}
  function openRecent(id){const x=readImports().find(i=>i.id===id);if(!x)return;reviewWorkout=clone(x.workout);renderSmartReview()}
  function persistReview(){syncReview();if(reviewWorkout?.importMeta?.id){const a=readImports();const i=a.findIndex(x=>x.id===reviewWorkout.importMeta.id);if(i>=0){a[i].workout=clone(reviewWorkout);a[i].confidence=reviewWorkout._ocrConfidence||0;a[i].date=new Date().toISOString();saveImports(a)}}}
  async function addDay(){persistReview();const tp = window.TrainMeiState||window.__tp;if(!tp){ alert('Training Planner is not ready yet.'); return; }tp.smartWorkout = smartDayData();if(!tp.currentUser){alert('Log in to add an imported workout to a synced day. You can still review it or save the import locally.');return;}if(typeof window.__tpApplySmartToDay === 'function'){await window.__tpApplySmartToDay();}}
  async function saveTemplate(){persistReview();const tp = window.TrainMeiState||window.__tp;if(!tp){ alert('Training Planner is not ready yet.'); return; }tp.smartWorkout = smartDayData();if(!tp.currentUser){alert('Log in to save the imported workout as a synced template. The OCR review remains stored locally.');return;}if(typeof window.__tpCreateSmartTemplate === 'function'){await window.__tpCreateSmartTemplate();}}document.addEventListener('click',e=>{const r=e.target.closest('[data-recent-id]');if(r){openRecent(r.dataset.recentId);return}if(e.target.closest('#close-smart-review')||e.target.closest('#smart-review-close')){persistReview();$i('#smart-review-modal').classList.remove('show');return}if(e.target.closest('#smart-review-add-day')){addDay();return}if(e.target.closest('#smart-review-template')){saveTemplate();return}const rem=e.target.closest('[data-rblock-remove]');if(rem){persistReview();const b=rem.closest('[data-rblock]');reviewWorkout.blocks.splice(Number(b.dataset.rblock),1);renderSmartReview();return}const add=e.target.closest('[data-rex-add]');if(add){persistReview();const b=reviewWorkout.blocks[Number(add.closest('[data-rblock]').dataset.rblock)];b.exercises[0]?.setGroups?.push(normalizeOCRSet({}));if(!b.exercises[0])b.exercises.push(makeExercise('New exercise',[{}]));renderSmartReview();return}const ea=e.target.closest('[data-ex-add]');if(ea){persistReview();const b=reviewWorkout.blocks[Number(ea.closest('[data-rblock]').dataset.rblock)];b.exercises.push(makeExercise('New exercise',[{}]));renderSmartReview();return}if(e.target.closest('[data-block-add]')){persistReview();reviewWorkout.blocks.push({name:`Block ${reviewWorkout.blocks.length+1}`,category:'Strength',exercises:[makeExercise('New exercise',[{}])]});renderSmartReview();return}const rs=e.target.closest('[data-rex-remove]');if(rs){persistReview();const row=rs.closest('[data-rex]'),parts=row.dataset.rex.split(':').map(Number),b=reviewWorkout.blocks[parts[0]],ex=b.exercises[parts[1]];ex.setGroups.splice(parts[2],1);if(!ex.setGroups.length)b.exercises.splice(parts[1],1);renderSmartReview();return}});const file=$i('#smart-screenshot-file');if(file)file.addEventListener('change',analyzeSmartScreenshot);const drop=$i('#smart-select-btn');if(drop){['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragover') }));drop.addEventListener('drop',e=>{const f=e.dataTransfer.files?.[0];if(!f)return;const dt=new DataTransfer();dt.items.add(f);file.files=dt.files;analyzeSmartScreenshot()})}renderRecentImports();window.analyzeSmartScreenshot=analyzeSmartScreenshot;window.smartDayData=smartDayData;})();
