/* TrainMei Phase 5 — Planning domain */
(()=>{
  const TP=window.TrainMeiState||window.__tp;
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=x=>TP.clone(x);
  const setVal=(sel,v)=>{const el=$(sel);if(el)el.value=v??''};
  const WEEKDAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
  const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
  const todayKey=TP.todayKey, dateKey=TP.dateKey;
  let planWeekKey=TP.todayKey();
  planWeekKey=(TP.dateKey(...(()=>{const d=new Date();const dow=(d.getDay()+6)%7;d.setDate(d.getDate()-dow);return [d.getFullYear(),d.getMonth(),d.getDate()]})()));
  const getPlan=()=>TP.planData;
  const templates=()=>TP.templatesCache||[];
  const loadDayLocal=TP.loadDayLocal;
function planMondayKey(date=new Date()){const d=new Date(date);d.setHours(12,0,0,0);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return dateKey(d.getFullYear(),d.getMonth(),d.getDate())}
function planWeekDates(mondayKey){const [y,m,d]=mondayKey.split('-').map(Number),base=new Date(y,m-1,d,12);return Array.from({length:7},(_,i)=>{const x=new Date(base);x.setDate(base.getDate()+i);return dateKey(x.getFullYear(),x.getMonth(),x.getDate())})}
function weekData(key){if(!getPlan().weeks[key])getPlan().weeks[key]={focus:'',notes:'',days:{}};if(!getPlan().weeks[key].days)getPlan().weeks[key].days={};return getPlan().weeks[key]}
function planDayInfo(key){const w=weekData(planWeekKey);if(!w.days[key])w.days[key]={templateId:'',title:'',status:'Planned'};return w.days[key]}
function templateForId(id){return templates().find(t=>String(t.id)===String(id))||null}
function planWeekLabel(key){const ds=planWeekDates(key),a=new Date(ds[0]+'T12:00:00'),b=new Date(ds[6]+'T12:00:00');return `${MONTHS[a.getMonth()]} ${a.getDate()} — ${MONTHS[b.getMonth()]} ${b.getDate()}, ${b.getFullYear()}`}
function renderPlan(){
 const w=weekData(planWeekKey),dates=planWeekDates(planWeekKey);const a=new Date(dates[0]+'T12:00:00');$('#plan-week-number').textContent=`WEEK ${getWeekNumber(a)}`;$('#plan-week-title').textContent=planWeekLabel(planWeekKey);setVal('#plan-week-focus',w.focus||'');setVal('#plan-week-notes',w.notes||'');
 $('#plan-week-grid').innerHTML=dates.map((key,i)=>{const dt=new Date(key+'T12:00:00'),info=planDayInfo(key),actual=loadDayLocal(key),title=info.title||actual.focus||actual.trainingCategory||'';const t=templateForId(info.templateId);const existing=t?esc(t.name):'';return `<article class="plan-day-card${key===todayKey()?' plan-day-today':''}"><div class="plan-day-head"><strong>${WEEKDAYS[i]}</strong><span class="plan-day-date">${MONTHS[dt.getMonth()].slice(0,3)} ${dt.getDate()}</span></div><div class="plan-day-body"><input class="plan-day-title" data-plan-day-title="${key}" value="${esc(info.title||'')}" placeholder="Session title"><div class="plan-day-template">${existing?`Template · ${existing}`:'Choose a template or open the day'}</div><select class="plan-day-select" data-plan-day-template="${key}"><option value="">No template</option>${templates().map(t=>`<option value="${esc(t.id)}" ${String(info.templateId)===String(t.id)?'selected':''}>${esc(t.name)}</option>`).join('')}</select><select class="plan-day-select" data-plan-day-status="${key}"><option ${info.status==='Planned'||!info.status?'selected':''}>Planned</option><option ${info.status==='Completed'?'selected':''}>Completed</option><option ${info.status==='Skipped'?'selected':''}>Skipped</option></select><div class="plan-day-buttons"><button class="btn" data-plan-open-day="${key}">Open</button><button class="btn" data-plan-apply-template="${key}">Apply</button></div></div></article>`}).join('');
 renderPlanBlocks();renderWeekTemplates();renderSeasonBlocks();
}
function getWeekNumber(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function renderPlanBlocks(){const el=$('#blocks-list');if(!el)return;if(!getPlan().blocks.length){el.innerHTML='<div class="empty-state">No training blocks yet. Add one to define a reusable multi-week focus.</div>';return}el.innerHTML=getPlan().blocks.map((b,i)=>`<div class="plan-row"><input data-plan-block-index="${i}" data-field="name" value="${esc(b.name)}" placeholder="Block name"><input data-plan-block-index="${i}" data-field="focus" value="${esc(b.focus||'')}" placeholder="Focus"><button data-plan-block-remove="${i}">×</button></div>`).join('')}
function renderWeekTemplates(){const el=$('#week-template-list');if(!el)return;if(!getPlan().weekTemplates.length){el.innerHTML='<div class="empty-state">Save a week once you like its structure, then reuse it later.</div>';return}el.innerHTML=getPlan().weekTemplates.map((t,i)=>`<div class="week-template-card"><div><strong>${esc(t.name||'Week template')}</strong><div class="week-template-meta">${(t.days||[]).filter(d=>d.templateId||d.title).length} planned days${t.focus?' · '+esc(t.focus):''}</div></div><div class="week-template-actions"><button class="btn" data-week-template-apply="${i}">Use</button><button class="btn danger" data-week-template-delete="${i}">×</button></div></div>`).join('')}
function renderSeasonBlocks(){const el=$('#season-block-list');if(!el)return;if(!getPlan().blocks.length){el.innerHTML='<div class="empty-state">Create a block such as Base, Build, Peak or Deload.</div>';return}el.innerHTML=getPlan().blocks.map((b,i)=>`<div class="season-block-card"><strong>${esc(b.name||'Training block')}</strong><input data-season-index="${i}" data-season-field="name" value="${esc(b.name||'')}" placeholder="Block name"><input data-season-index="${i}" data-season-field="start" value="${esc(b.start||'')}" type="date"><input data-season-index="${i}" data-season-field="end" value="${esc(b.end||'')}" type="date"><textarea data-season-index="${i}" data-season-field="focus" placeholder="Block focus">${esc(b.focus||'')}</textarea><div class="season-block-actions"><button class="btn danger" data-season-remove="${i}">Remove</button></div></div>`).join('')}
function saveWeekTemplate(){const w=weekData(planWeekKey),name=prompt('Week template name:',`Week ${getWeekNumber(new Date(planWeekKey+'T12:00:00'))}`);if(!name)return;getPlan().weekTemplates.push({name:name.trim(),focus:w.focus||'',days:planWeekDates(planWeekKey).map(k=>clone(planDayInfo(k)))}) ;renderPlan();TP.savePlanCloud()}
function applyWeekTemplate(i){const t=getPlan().weekTemplates[i];if(!t)return;const dates=planWeekDates(planWeekKey);dates.forEach((k,idx)=>{weekData(planWeekKey).days[k]=clone((t.days||[])[idx]||{templateId:'',title:'',status:'Planned'})});weekData(planWeekKey).focus=t.focus||'';renderPlan();TP.savePlanCloud();TP.setStatus('Week template applied')}
async function applyPlanTemplate(key){const info=planDayInfo(key),id=info.templateId;if(!id){TP.setStatus('Choose a template first');return}const t=templateForId(id);if(!t?.data){TP.setStatus('Template unavailable');return}TP.selectedDateKey=key;TP.currentDay=TP.normalizeDay(clone(t.data));await TP.saveDay();TP.monthIndicators[key]=TP.currentDay;info.title=TP.currentDay.focus||t.name||'';info.status='Planned';weekData(planWeekKey).days[key]=info;renderPlan();TP.setStatus('Template applied to day')}
function movePlanWeek(){const source=weekData(planWeekKey);const d=new Date(planWeekKey+'T12:00:00');d.setDate(d.getDate()+7);const target=dateKey(d.getFullYear(),d.getMonth(),d.getDate());if(!confirm('Move this plan to the next week? The current Plan week will be cleared; Calendar workouts are not deleted.'))return;getPlan().weeks[target]=clone(source);delete getPlan().weeks[planWeekKey];planWeekKey=target;renderPlan();TP.savePlanCloud();TP.setStatus('Plan moved to next week')}
function clearPlannedWeek(){if(!confirm('Clear the Plan entries for this week? Existing Calendar workouts will not be deleted.'))return;const w=weekData(planWeekKey);w.focus='';w.notes='';w.days={};renderPlan();TP.savePlanCloud();TP.setStatus('Planned week cleared')}
async function duplicatePlanWeek(){const source=weekData(planWeekKey),from=planWeekKey;const d=new Date(from+'T12:00:00');d.setDate(d.getDate()+7);const target=dateKey(d.getFullYear(),d.getMonth(),d.getDate());getPlan().weeks[target]=clone(source);planWeekKey=target;renderPlan();await TP.savePlanCloud();TP.setStatus('Week duplicated')}
function addSeasonBlock(){getPlan().blocks.push({name:'',start:'',end:'',focus:''});renderPlan()}
function addPlanBlock(){addSeasonBlock()}
function setPlanWeekFrom(delta){const d=new Date(planWeekKey+'T12:00:00');d.setDate(d.getDate()+delta*7);planWeekKey=dateKey(d.getFullYear(),d.getMonth(),d.getDate());renderPlan()}
function openPlanDay(key){TP.selectedDateKey=key;TP.openDay(key)}


  window.TrainMeiPlanning={planMondayKey,planWeekDates,weekData,planDayInfo,planWeekLabel,renderPlan,renderPlanBlocks,renderWeekTemplates,renderSeasonBlocks,saveWeekTemplate,applyWeekTemplate,applyPlanTemplate,movePlanWeek,clearPlannedWeek,duplicatePlanWeek,addSeasonBlock,addPlanBlock,setPlanWeekFrom,openPlanDay,getWeekNumber,getPlanWeekKey:()=>planWeekKey,setPlanWeekKey:v=>{if(/^\d{4}-\d{2}-\d{2}$/.test(v))planWeekKey=v},savePlanCloud:async()=>{localStorage.setItem('training-planner:plan',JSON.stringify(getPlan()));if(!TP.currentUser){TP.setStatus('Plan saved locally');return}const {error}=await TP.supabaseClient().from('training_plans').upsert({user_id:TP.currentUser.id,data:getPlan(),updated_at:new Date().toISOString()},{onConflict:'user_id'});TP.setStatus(error?'Plan saved locally — cloud table missing or unavailable':'Plan saved')}};
})();
